<?php if ($this->pageCount): ?>
<div id="paginator" align="center"> 
<!-- Previous page link -->
<nav>
<ul class="pagination">
<?php if (isset($this->previous)): ?>
    <li class="page-item">
        <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">Anterior</a>
    </li>
<?php else: ?>
    <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Anterior</span>
      </a>
    </li>
<!--     <span>&lt; Previous</span> | -->
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <li class="page-item">
            <a class="page-link" href="<?php echo $this->url(array('page' => $page)); ?>">
                <?php echo $page; ?>
            </a>
        </li>
    <?php else: ?>
            <li class="page-item disabled"><a class="page-link" href="#"><?php echo $page; ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <li class="page-item">
        <a class="page-link" href="<?php echo $this->url(array('page' => $this->next)); ?>">
            Próximo
        </a>
    </li>
<?php else: ?>
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Anterior</span>
      </a>
    </li>
<?php endif; ?>
</ul>
</nav>
</div>
<?php endif; ?>