<div class=" col-lg-4 col-lg-offset-4">
  <div align="center"><h1 class="page-header">Login</h1></div>
  <form action="<?php echo $this->baseUrl("usuario/autenticar");?>" method="post">
    <div class="form-group">
       <label for="email">E-mail:</label><input type="text" class="form-control" value="<?php echo $this->row['email'] ?>" name="email" />
    </div>
    <div class="form-group">
       <label for="senha">Senha:</label><input type="password" class="form-control" value="<?php echo $this->row['senha'] ?>" name="senha" />
    </div>
    <div class="form-group" align="center">
       <a class="btn btn-success"><h5>Entrar &nbsp;<span class="glyphicon glyphicon-log-in"></span></h5></a>
    </div>
  </form>
</div> 
